
spring:
  datasource:
    url: "${DB_URL:jdbc:postgresql://postgres-db:5432/identity_service}"
    driverClassName: "org.postgresql.Driver"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:123}"
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "${JWT_SIGNERKEY}"
  valid-duration: 20
  refreshable-duration: 40